# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - randompeeps

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-api:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: Install dependencies
        run: dotnet restore src
  
      - name: Build with dotnet
        run: dotnet build --configuration Release src

      - name: dotnet publish
        run: dotnet publish src -c Release

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: random-peeps.api
          path: src/bin/Release/net8.0/publish

  deploy:
    runs-on: ubuntu-latest
    needs: build-api
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: random-peeps.api
      
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'randompeeps'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_70DBFB9AEBA94A35BD9D587BF600E994 }}
